{{- if .Values.falcoagent.enabled -}}
{{- $_ := set . "Label" "falco" }}
{{- $_ := set . "Config" .Values.falcoagent }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  {{- include "metadata" . }}
spec:
  {{ include "cronjob-spec" . | nindent 2 | trim }}
  jobTemplate:
    spec:
      {{ include "job-spec" . | nindent 6 | trim }}
      template:
        spec:
          {{ include "job-template-spec" . | indent 10 | trim }}
          containers:
          - name: {{ .Label }}
            image: "{{ .Values.cronjobExecutor.image.repository }}:{{ .Values.cronjobExecutor.image.tag }}"
            imagePullPolicy: Always
            {{- with $.Values.cronjobs.imagePullSecret }}
            imagePullSecrets:
                - name: {{ . }}
            {{- end }}
            resources:
                {{- toYaml .Config.resources | nindent 12 }}
            volumeMounts:
            - name: output
              mountPath: /output
            command: ["sh"]
            args:
                - -c
                - |
                  curl http://falco-agent:3031/output -o /tmp/falco.json && mv /tmp/falco.json /output/falco.json        
            {{ include "security-context" . | indent 12 | trim }}
          {{ include "uploaderContainer" . | indent 10 | trim }}
  {{- end -}}